### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by DuncanLithgow** [twpride/three.cad#2]
Please add a license so I can consider adding three.cad to the wiki.osarch.org software directory.

I suggest a copy left reciprocal license like GPL 2 or 3

**Comment by aguajardo** [comment]
Hi, have you considered adding a license to evaluate commercial use? It still needs some features but without a license it is too risky to further develop.

**Comment by twpride** [comment]
@DuncanLithgow apologize for the delay. I was forced to use a GPL 3 license because my the app links to this [project](https://github.com/solvespace/solvespace)

**Comment by twpride** [comment]
@DuncanLithgow apologize for the delay. I was forced to use a GPL 3 license because the app links to this [project](https://github.com/solvespace/solvespace)
